spring:
  application:
    name: Spring Boot Lab

app:
  # Notification Configuration
  notification:
    enabled: true
    type: email  # Options: email, sms
    email:
      host: smtp.example.com
      port: 587
      from: lab@example.com
    sms:
      api-key: your-api-key-here
      provider: twilio